apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  selector:
    app: patient-ms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8081
      nodePort: 30080